# Site settings
title:       The Codery
email:       bk@thecodery.co
description: We build products on the web.
url:         http://www.thecodery.co

# Build settings
markdown: kramdown
permalink: pretty
