# Site settings
title:       The Codery
email:       bk@thecodery.co
description: The Codery is a digital design agency that helps take your idea and bring it to fruition.
url:         http://www.thecodery.co

# Build settings
markdown: kramdown
permalink: pretty
